### ISSUE TITLE
Refactor pui-fluid to only apply widgets

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeui#71]
pui-fluid has;

```css
.pui-fluid * {
    box-sizing: border-box;
    -webkit-box-sizing:border-box;
    -moz-box-sizing: border-box;
} 
```
Instead we should apply to our widget wrapper elements only.
